apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "theater.fullname" . }}
  labels:
    app: {{ template "theater.name" . }}
    chart: {{ template "theater.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "theater.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "theater.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "theater.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: theater-port
              containerPort: {{ .Values.servicePort }}

