apiVersion: v1
kind: Service
metadata:
  name: {{ template "theater.fullname" . }}
  labels:
    app: {{ template "theater.name" . }}
    chart: {{ template "theater.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: theater-port
      port: {{ .Values.servicePort }}
  selector:
    app: {{ template "theater.name" . }}
    release: {{ .Release.Name }}
